# Generated by Django 4.0.2 on 2022-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=50)),
                ('ultimoNome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('clientID', models.IntegerField()),
                ('contrato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservaID', models.IntegerField()),
                ('horaChegada', models.TimeField()),
                ('horaSaida', models.TimeField()),
                ('duracao', models.TimeField()),
                ('data', models.DateField()),
            ],
        ),
    ]
